apiVersion: apps/v1
kind: Deployment
metadata:
  name: a3-auth-frontend
spec:
  selector:
    matchLabels:
      app: a3-auth-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: a3-auth-frontend
    spec:
      containers:
        - name: a3-auth-frontend
          image: a3-auth-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
