apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  selector:
    matchLabels:
      app: my-react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: my-react-app
          imagePullPolicy: Never
          ports:
            - containerPort: 80
