apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-first-app
spec:
  selector:
    matchLabels:
      app: react-first-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-first-app
    spec:
      containers:
        - name: react-first-app
          image: react-first-app
          imagePullPolicy: Never
          ports:
            - containerPort: 80
