kind: Service
apiVersion: v1
metadata:
  name: a3-auth-frontend-service
spec:
  selector:
    app: a3-auth-frontend
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 9095
      targetPort: 80
  type: NodePort
